tools:
  php_mess_detector:
    extensions:
      - php
      - inc
  php_code_sniffer:
    config:
      standard: Drupal
    extensions:
      - php
      - inc
  php_cpd:
    names:
      - '*.php'
      - '*.inc'
  php_loc:
    names:
      1: '*.inc'
      2: '*.php'
  php_pdepend:
    suffixes:
      - php
      - inc
  external_code_coverage:
    # Wait up to thirty minutes for code coverage.
    timeout: 1800
