# Configuration for Travis CI at http://travis-ci.org/#!/reload/deployotron
language: php
php:
  - 5.4
env:
  - DRUSH_VERSION=7.2.0
  - DRUSH_VERSION=8.0.5
  - DRUSH_VERSION=dev-master
install:
  # We have to checkout drush and run composer install, rather than
  # using composer global require, as the autoload-dev to load the
  # test base classes is only added for root projects.
  - composer self-update
  - export PATH="$HOME/drush:$PATH"
  - export DRUSH_DIR=~/drush
  - git clone https://github.com/drush-ops/drush.git $DRUSH_DIR
  - cd $DRUSH_DIR 
  - git checkout $DRUSH_VERSION
  # Install Drush dependencies.
  - composer install --prefer-source
  - phpenv rehash
  - cd -
  - mkdir cov
before_script:
  - export BOOTSTRAP=$DRUSH_DIR/tests/bootstrap.inc
script: phpunit --bootstrap=$BOOTSTRAP --coverage-clover=`pwd`/cov/clover.xml tests
notifications:
  flowdock: 78b17a3314f1bac5207d8e65e391287b
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover cov/clover.xml
