# Configuration for Travis CI at http://travis-ci.org/#!/xendk/drake
language: php
php:
  - 5.3
env:
  - UNISH_DB_URL=mysql://root:@127.0.0.1 DRUSH_VERSION=5.10.0.0 PATCH="5.10.0...coverage-5.10.0"
  - UNISH_DB_URL=mysql://root:@127.0.0.1 DRUSH_VERSION=6.2.0.0 PATCH="6.2.0...coverage-6.2.0"
install:
  - pear channel-discover pear.drush.org
  - pear install drush/drush-$DRUSH_VERSION
  - composer install --dev --no-interaction --prefer-source
  - export README=`pear list-files drush/drush-$DRUSH_VERSION | grep drush.php | awk '{print $2}'`
  - export DRUSH_DIR=`dirname $README`
  - cd $DRUSH_DIR
  - wget https://github.com/xendk/drush/compare/$PATCH.diff -O coverage.patch
  - patch -p1 < coverage.patch
  - phpenv rehash
  - cd -
  - mkdir cov
before_script:
  - export BOOTSTRAP=`pear list-files drush/drush-$DRUSH_VERSION | grep drush_testcase.inc | awk '{print $2}'`
script: phpunit --bootstrap=$BOOTSTRAP --coverage-clover=`pwd`/cov/clover.xml tests
notifications:
  flowdock: 78b17a3314f1bac5207d8e65e391287b
after_script:
  - php vendor/bin/coveralls -v
